name: Publish


on: workflow_dispatch


env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test GameTests -c Release --no-restore --no-build

      - name: Publish
        run: dotnet publish SnakeGame -c Release -o SnakeGame/publish --no-restore

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: SnakeGame/publish/
          if-no-files-found: error
          overwrite: true
